## Pre processing

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

In [80]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [0]:
x = iris.data
y = iris.target

In [82]:
from sklearn.preprocessing import StandardScaler

# scaler the data
scaler_x = StandardScaler()
x = scaler_x.fit_transform(x)
x.shape

(150, 4)

In [83]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

from sklearn.compose import ColumnTransformer

y = y.reshape(-1, 1)

# divide the y in array of 3 items (possible items classify by the dataset)
transformer = ColumnTransformer(
    transformers=[
        (
          "OneHot",        # Just a name
          OneHotEncoder(), # The transformer class
          [0]              # The column(s) to be applied on.
         )
    ],
    remainder='passthrough' # donot apply anything to the remaining columns
)

y = transformer.fit_transform(y)
print(y)
print(y.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [85]:
from sklearn.model_selection import train_test_split
x_training, x_test, y_training, y_test = train_test_split(x, y, test_size=0.3)
print(x_training.shape)
print(x_test.shape)

(105, 4)
(45, 4)


## Manipulate

In [93]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
neurons_input = x.shape[1] # 4
neurons_hidden = int( np.ceil( (x.shape[1] + y.shape[1]) / 2 ) ) # 4
neurons_out = y.shape[1] # 3

In [0]:
weights = { 
    'hidden': tf.Variable(tf.random_normal([neurons_input, neurons_hidden])),
    'out':  tf.Variable(tf.random_normal([neurons_hidden, neurons_out]))
    }

In [0]:
bias = {
    'hidden': tf.Variable(tf.random_normal([neurons_hidden])),
    'out': tf.Variable(tf.random_normal([neurons_out]))
}

In [0]:
x_placeholder = tf.placeholder('float', [None, neurons_input])
y_placeholder = tf.placeholder('float', [None, neurons_out])

In [0]:
def ml_calculation(x, weights, bias):
  layer_hidden = tf.add( tf.matmul(x, weights['hidden']), bias['hidden'])
  layer_hidden_active = tf.nn.relu(layer_hidden)
  layer_out = tf.add( tf.matmul(layer_hidden_active, weights['out']), bias['out'] )
  return layer_out

In [0]:
model = ml_calculation( x_placeholder, weights, bias )

In [0]:
error = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits_v2(logits = model, labels = y_placeholder ) )
optmizer = tf.train.AdamOptimizer(learning_rate= 0.0001).minimize(error)

In [0]:
batch_size = 8
batch_total = int(len(x_training) / batch_size)

In [107]:
x_batches = np.array_split(x_training, batch_total)
x_batches

[array([[-9.00681170e-01,  7.88807586e-01, -1.28338910e+00,
         -1.31544430e+00],
        [ 7.95669016e-01, -1.31979479e-01,  9.90107977e-01,
          7.90670654e-01],
        [ 5.53333275e-01, -1.74335684e+00,  3.64896281e-01,
          1.32509732e-01],
        [ 5.53333275e-01, -1.28296331e+00,  7.05920842e-01,
          9.22302838e-01],
        [ 1.03800476e+00,  5.58610819e-01,  1.10378283e+00,
          1.18556721e+00],
        [ 3.10997534e-01, -5.92373012e-01,  5.35408562e-01,
          8.77547895e-04],
        [-4.16009689e-01, -1.51316008e+00,  2.38717193e-02,
         -1.30754636e-01],
        [-7.79513300e-01,  2.40018495e+00, -1.28338910e+00,
         -1.44707648e+00],
        [ 1.89829664e-01, -8.22569778e-01,  7.62758269e-01,
          5.27406285e-01]]),
 array([[ 1.03800476, -0.13197948,  0.70592084,  0.65903847],
        [ 0.18982966, -0.13197948,  0.59224599,  0.79067065],
        [-1.74885626,  0.32841405, -1.39706395, -1.3154443 ],
        [ 0.67450115, -0.5923

In [115]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for epoch in range(3000):
    error_medium = 0.0
    batch_total = int(len(x_training) / batch_size)
    x_batches = np.array_split(x_training, batch_total)
    y_batches = np.array_split(y_training, batch_total)

    for i in range(batch_total):
        x_batch, y_batch = x_batches[i], y_batches[i] 
        _, cost = sess.run([optmizer, error], feed_dict= { x_placeholder: x_batch, y_placeholder: y_batch })
        error_medium += cost / batch_total

    if epoch % 500 == 0:
      print('Epoch ' + str(epoch + 1) + ' erro: ' + str(error_medium) )

    weights_final, bias_final = sess.run([weights, bias])

Epoch 1 erro: 3.359417365147517
Epoch 501 erro: 0.5123579318706806
Epoch 1001 erro: 0.21379451396373603
Epoch 1501 erro: 0.13599830521987036
Epoch 2001 erro: 0.0976528935134411
Epoch 2501 erro: 0.07697608629957987


In [116]:
weights_final

{'hidden': array([[ 0.50816065, -0.37102714,  0.29878032, -0.4987421 ],
        [-0.41746983,  0.09131236, -1.1371527 , -0.00811028],
        [ 0.6669909 ,  0.90253955,  0.9577407 ,  2.0503838 ],
        [ 1.6259292 , -0.5280943 ,  1.110857  ,  1.9781266 ]],
       dtype=float32), 'out': array([[-2.6152174 ,  0.8801336 ,  0.19901493],
        [ 1.2691445 ,  0.7342005 , -1.7732584 ],
        [-1.6194898 , -0.86946744,  0.25947464],
        [-1.9328493 , -1.6720581 ,  1.499492  ]], dtype=float32)}

In [118]:
bias_final

{'hidden': array([ 3.1060872 ,  1.2999556 , -0.16372363, -0.70950305], dtype=float32),
 'out': array([ 3.8171055 , -0.88643736, -1.2231512 ], dtype=float32)}

In [0]:
# previsions
previsions_test = ml_calculation(x_placeholder, weights_final, bias_final)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  r1 = sess.run(previsions_test, feed_dict={x_placeholder: x_test})
  r_softmax = sess.run(tf.nn.softmax(r1))

  # the greater value
  result_final = sess.run(tf.argmax(r_softmax, 1))

In [122]:
r1

array([[-8.5984116e+00,  1.6436393e+00, -1.6031038e+00],
       [ 5.1420417e+00, -1.1996138e-01, -3.0743623e+00],
       [-3.5196302e+00,  2.6926806e+00, -2.6890464e+00],
       [ 5.3100348e+00, -2.2777498e-02, -3.3090830e+00],
       [-7.0150080e+00,  1.8403435e+00, -1.2681807e+00],
       [-1.7859756e+01, -1.7623248e+00,  2.0119379e+00],
       [-7.7864790e+00,  1.2685833e+00, -1.4006363e+00],
       [-7.2238598e+00,  2.0543237e+00, -1.6847441e+00],
       [ 5.3363552e+00, -7.5510740e-03, -3.3458583e+00],
       [ 5.4281368e+00,  4.5544624e-02, -3.4740963e+00],
       [-3.0500991e+00,  1.7020407e+00, -2.9548423e+00],
       [-5.4002886e+00,  1.2740853e+00, -2.7204690e+00],
       [ 5.3593302e+00,  5.7399869e-03, -3.3779593e+00],
       [-2.4411128e+00,  1.9477499e+00, -2.6904294e+00],
       [-1.2401597e+01,  5.5374902e-01, -4.3842107e-01],
       [-1.5998790e+01, -8.3097070e-01,  1.3955231e+00],
       [ 5.5260096e+00,  1.0216397e-01, -3.6108446e+00],
       [-1.6576357e+01, -5.4105

In [125]:
r_softmax

array([[3.4304001e-05, 9.6252286e-01, 3.7442811e-02],
       [9.9457461e-01, 5.1567792e-03, 2.6871904e-04],
       [1.9914473e-03, 9.9343878e-01, 4.5696893e-03],
       [9.9501389e-01, 4.8063807e-03, 1.7971895e-04],
       [1.3650001e-04, 9.5711243e-01, 4.2751167e-02],
       [2.2907443e-09, 2.2438945e-02, 9.7756106e-01],
       [1.0921615e-04, 9.3508363e-01, 6.4807184e-02],
       [9.1262344e-05, 9.7668672e-01, 2.3221955e-02],
       [9.9507755e-01, 4.7536572e-03, 1.6874053e-04],
       [9.9529028e-01, 4.5742476e-03, 1.3544377e-04],
       [8.4794741e-03, 9.8219359e-01, 9.3269236e-03],
       [1.2384916e-03, 9.8070121e-01, 1.8060252e-02],
       [9.9513215e-01, 4.7081052e-03, 1.5970708e-04],
       [1.2146524e-02, 9.7838736e-01, 9.4661890e-03],
       [1.7242448e-06, 7.2951508e-01, 2.7048320e-01],
       [2.5190834e-08, 9.7396433e-02, 9.0260357e-01],
       [9.9550253e-01, 4.3903193e-03, 1.0714133e-04],
       [1.5388505e-08, 1.4165743e-01, 8.5834259e-01],
       [4.3238694e-15, 2.659

In [127]:
result_final

array([1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 0,
       1, 2, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2,
       0])

In [129]:
y_test2 = np.argmax(y_test, 1)
y_test2

array([1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 2, 2, 0, 2, 2, 1, 2, 0,
       1, 2, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2,
       0])

In [131]:
from sklearn.metrics import accuracy_score
rate_acc = accuracy_score(y_test2, result_final)
rate_acc

0.9777777777777777