## Simple Perceptron

In [0]:
import tensorflow.compat.v1 as tf
import numpy as np
tf.disable_v2_behavior()

In [81]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
x

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [82]:
# OR result expression
y = np.array([[0.0], [1.0], [1.0], [1.0]])

# AND result expression
# y = np.array([[0.0], [0.0], [0.0], [1.0]])

y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [83]:
w = tf.Variable(tf.zeros([2,1], dtype=tf.float64))

type(w)

tensorflow.python.ops.variables.RefVariable

In [0]:
def step_function(value):
   return tf.cast(  tf.math.greater_equal(value, 1) , dtype=tf.float64 )

In [0]:
# multiply and sum
layer_out = tf.matmul(x, w)

In [86]:
print(w)

<tf.Variable 'Variable_6:0' shape=(2, 1) dtype=float64_ref>


In [0]:
layer_out_activation = step_function(layer_out)

In [0]:
error = tf.subtract(y, layer_out_activation)

In [0]:
# update errors

# weight(n + 1) = weight(n) + (learning_rate * input * error)

# inputs * errors
delta = tf.matmul(x, error, transpose_a=True)
# delta * learning rate * weight
# tf.asign will update the variable w (weight)
training = tf.assign( w, tf.add( w, tf.multiply( delta, 0.1 ) ) )


In [90]:
with tf.compat.v1.Session() as sess:
  sess.run(tf.compat.v1.global_variables_initializer())
  # print(sess.run(w))
  # print(sess.run(layer_out))

  # print(sess.run( step_function(-1) ))
  # print("\n")
  # print(sess.run(layer_out_activation))
  # print("\n")
  # print(sess.run(error))
  # print("\n New weights")
  # print(sess.run(training))

  epochs = 0

  for i in range(15):
    epochs += 1
    error_total, _ = sess.run([error, training])
    # print(error_total)
    # sum of errors
    error_sum = tf.reduce_sum(error_total)
    print(sess.run(w))
    print( 'Epochs', epochs,' Error: ', sess.run(error_sum) )

    if error_sum.eval() == 0.0:
      break


  w_final = sess.run(w)

[[0.2]
 [0.2]]
Epochs 1  Error:  3.0
[[0.4]
 [0.4]]
Epochs 2  Error:  3.0
[[0.6]
 [0.6]]
Epochs 3  Error:  3.0
[[0.7]
 [0.7]]
Epochs 4  Error:  2.0
[[0.8]
 [0.8]]
Epochs 5  Error:  2.0
[[0.9]
 [0.9]]
Epochs 6  Error:  2.0
[[1.]
 [1.]]
Epochs 7  Error:  2.0
[[1.]
 [1.]]
Epochs 8  Error:  0.0


In [91]:
w_final

array([[1.],
       [1.]])

In [92]:
# test
layer_out_test = tf.matmul(x, w_final)
layer_out_activation_test = step_function(layer_out_test)

with tf.Session() as sess:
  sess.run(tf.compat.v1.global_variables_initializer())
  print(sess.run(layer_out_activation_test))

[[0.]
 [1.]
 [1.]
 [1.]]
