In [1]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

In [3]:
a = tf.constant([9,8,7], name='a')
b = tf.constant([1,2,3], name='b')
sum_vectors = a + b

In [6]:
# sum between vectors
with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer())
    print(sess.run(sum_vectors))
    

[10 10 10]


In [15]:
# operations with matrix
matrix_a = tf.constant([[1,2], [3,4]], name='matrix_a')
matrix_b = tf.constant([[2, 4], [5, 6]], name='matrix_b')
print(matrix_a)
print(matrix_b)
# sum between matrices
sum_matrices = tf.add(matrix_a, matrix_b)
multiplication_matrices = matrix_a * matrix_b

Tensor("matrix_a_4:0", shape=(2, 2), dtype=int32)
Tensor("matrix_b_4:0", shape=(2, 2), dtype=int32)


In [18]:
with tf.Session() as sess:
    print('matrix a')
    print(sess.run(matrix_a))
    print('\nmatrix b')
    print(sess.run(matrix_b))
    print('\n sum matrices')
    print(sess.run(sum_matrices))
    print('\n multiplication matrices')
    print(sess.run(multiplication_matrices))

matrix a
[[1 2]
 [3 4]]

matrix b
[[2 4]
 [5 6]]

 sum matrices
[[ 3  6]
 [ 8 10]]

 multiplication matrices
[[ 2  8]
 [15 24]]


In [21]:
# sum matrix with diferent 
matrix_a1 = tf.constant([[1, 2, 3], [3, 4, 5]], name='matrix_a')
matrix_b1 = tf.constant([[2], [1]], name='matrix_b')
print(matrix_a)
print(matrix_b)

sum_matrices_diff = tf.add(matrix_a1, matrix_b1)

with tf.Session() as sess:
    print('\n')
    print(sess.run(matrix_a1))
    print('\n')
    print(sess.run(matrix_b1))
    print('\n')
    print(sess.run(sum_matrices_diff))

Tensor("matrix_a_4:0", shape=(2, 2), dtype=int32)
Tensor("matrix_b_4:0", shape=(2, 2), dtype=int32)


[[1 2 3]
 [3 4 5]]


[[2]
 [1]]


[[3 4 5]
 [4 5 6]]
